# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c632c16823791c896eee134ba1dae02db2d64cf257d91708ab2d94ebd1cdda3b677dce7b31d8c9f72d2aacf210335054cc5ca300c7e21997dec381418ca078e0

test:
  secret_key_base: 861b9ba1da0e8c498019c281e804540eba9d1afdf75c804bd011f3ae5038a20903b0a25c428d3f68dd2879d9a1a30a971052d5a08ba5ce0ce4df925eb4c24fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
